.TH "gksu-properties" "1" "2008-09-02"

.SH "NAME" 
gksu-properties \- Configure the behaviour of gksu 

.SH "SYNOPSIS"
.PP
.B gksu-properties 


.SH "DESCRIPTION" 
.PP
This manual page documents briefly the \fBgksu-properties\fR command.
.PP
.B gksu-properties 
allows you to define how 
.BR gksu (1)
grants the privileges and locks your input devices (mouse, keyboard...).

.\"No options from source
.SH "SEE ALSO"
.BR gksu (1),\  su \ (1), \ sudo (1)

.SH "AUTHORS"
.PP
Gustavo Noronha Silva <kov@debian.org>
.br
Allan Douglas <allan_douglas@gmx.net>

This manual page was written by Francois Wendling <frwendling@free.fr> for the
Debian GNU/Linux system (but may be used by others).
